# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='amount_paid',
        ),
    ]
