# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordered_products', '0002_orderedproducts_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedproducts',
            old_name='productsid',
            new_name='ProductVariantsid',
        ),
    ]
