# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordered_products', '0003_auto_20180710_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedproducts',
            old_name='ProductVariantsid',
            new_name='ProductVariantid',
        ),
    ]
