# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordered_products', '0004_auto_20180710_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedproducts',
            old_name='ProductVariantid',
            new_name='product_variantid',
        ),
    ]
