# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-28 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordername', models.CharField(max_length=255)),
                ('mode_of_payment', models.CharField(choices=[(b'cod', b'Cash_On_Delivery'), (b'pesapal', b'Pesapal'), (b'mpesa', b'M-Pesa')], max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('modifieddate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
