# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
