# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-28 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_type', '0001_initial'),
        ('store', '0001_initial'),
        ('product_subtype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255)),
                ('product_description', models.CharField(max_length=255)),
                ('feature_photo', models.ImageField(upload_to=b'')),
                ('regular_price', models.CharField(max_length=255)),
                ('sale_price', models.CharField(blank=True, max_length=255, null=True)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('modifieddate', models.DateTimeField(auto_now=True)),
                ('product_subtypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_subtype.ProductSubType')),
                ('product_typeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_type.ProductType')),
                ('storeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
        ),
    ]
